In [3]:
import numpy as np


# ==========================
# Gram-Schmidt QR Decomposition
# ==========================
def qr_decomposition(A):
    n = len(A)

    Q = np.zeros((n, n), dtype=float)
    R = np.zeros((n, n), dtype=float)

    for j in range(n):

        v = A[:, j].copy()

        for i in range(j):
            R[i][j] = np.dot(Q[:, i], A[:, j])
            v = v - (R[i][j] * Q[:, i])

        R[j][j] = np.linalg.norm(v)
        Q[:, j] = v / R[j][j]

    return Q, R


# ==========================
# QR Iteration (10x)
# ==========================
def qr_iteration(A, max_iter=10):

    Ak = A.astype(float)

    print("A0 =")
    print(Ak)
    print("=" * 40)

    for k in range(max_iter):

        # QR decomposition
        Q, R = qr_decomposition(Ak)

        # Ak+1 = RQ
        Ak = np.dot(R, Q)

        print("Iterasi ke-", k + 1)

        print("Q =")
        print(Q)

        print("R =")
        print(R)

        print("A" + str(k + 1) + " =")
        print(Ak)

        print("=" * 40)

    return Ak


def main():

    A = np.array([
        [2, 1],
        [1, 2]
    ], dtype=float)

    hasil = qr_iteration(A, 10)

    print("\nMatriks akhir:")
    print(hasil)

    print("\nEigenvalue:")
    print(np.diag(hasil))


if __name__ == "__main__":
    main()

A0 =
[[2. 1.]
 [1. 2.]]
Iterasi ke- 1
Q =
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
R =
[[2.23606798 1.78885438]
 [0.         1.34164079]]
A1 =
[[2.8 0.6]
 [0.6 1.2]]
Iterasi ke- 2
Q =
[[ 0.97780241 -0.20952909]
 [ 0.20952909  0.97780241]]
R =
[[2.86356421 0.83811635]
 [0.         1.04764544]]
A2 =
[[2.97560976 0.2195122 ]
 [0.2195122  1.02439024]]
Iterasi ke- 3
Q =
[[ 0.99729001 -0.07357057]
 [ 0.07357057  0.99729001]]
R =
[[2.98369553 0.2942823 ]
 [0.         1.00546452]]
A3 =
[[2.99726027 0.0739726 ]
 [0.0739726  1.00273973]]
Iterasi ke- 4
Q =
[[ 0.99969559 -0.02467256]
 [ 0.02467256  0.99969559]]
R =
[[2.99817296 0.09869024]
 [0.         1.00060938]]
A4 =
[[2.99969521 0.0246876 ]
 [0.0246876  1.00030479]]
Iterasi ke- 5
Q =
[[ 0.99996613 -0.00822976]
 [ 0.00822976  0.99996613]]
R =
[[2.9997968  0.03291902]
 [0.         1.00006774]]
A5 =
[[2.99996613 0.00823031]
 [0.00823031 1.00003387]]
Iterasi ke- 6
Q =
[[ 0.99999624 -0.00274346]
 [ 0.00274346  0.99999624]]
R =
[[2.999