# Tugas EigenValue

## menggunakan desimal

In [7]:
import numpy as np

def qr_decomposition(A):
    n = len(A)

    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for j in range(n):

        v = A[:, j].copy()

        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

def qr_iteration(A, jumlah_iterasi=10):

    Ak = A.astype(float)

    print("A0 =")
    print(Ak)
    print()

    for k in range(jumlah_iterasi):

        print("=" * 40)
        print("ITERASI", k + 1)

        # QR decomposition
        Q, R = qr_decomposition(Ak)

        print("\nQ =")
        print(Q)

        print("\nR =")
        print(R)

        # Ak+1 = RQ
        Ak = R @ Q

        print("\nA{} =".format(k + 1))
        print(Ak)
        print()

    return Ak

In [8]:
A = np.array([
    [2, 1],
    [1, 2]
], dtype=float)

hasil = qr_iteration(A, 10)

print("=" * 40)
print("MATRIKS AKHIR")
print(hasil)

print("\nEIGENVALUE:")
print(np.diag(hasil))

A0 =
[[2. 1.]
 [1. 2.]]

ITERASI 1

Q =
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

R =
[[2.23606798 1.78885438]
 [0.         1.34164079]]

A1 =
[[2.8 0.6]
 [0.6 1.2]]

ITERASI 2

Q =
[[ 0.97780241 -0.20952909]
 [ 0.20952909  0.97780241]]

R =
[[2.86356421 0.83811635]
 [0.         1.04764544]]

A2 =
[[2.97560976 0.2195122 ]
 [0.2195122  1.02439024]]

ITERASI 3

Q =
[[ 0.99729001 -0.07357057]
 [ 0.07357057  0.99729001]]

R =
[[2.98369553 0.2942823 ]
 [0.         1.00546452]]

A3 =
[[2.99726027 0.0739726 ]
 [0.0739726  1.00273973]]

ITERASI 4

Q =
[[ 0.99969559 -0.02467256]
 [ 0.02467256  0.99969559]]

R =
[[2.99817296 0.09869024]
 [0.         1.00060938]]

A4 =
[[2.99969521 0.0246876 ]
 [0.0246876  1.00030479]]

ITERASI 5

Q =
[[ 0.99996613 -0.00822976]
 [ 0.00822976  0.99996613]]

R =
[[2.9997968  0.03291902]
 [0.         1.00006774]]

A5 =
[[2.99996613 0.00823031]
 [0.00823031 1.00003387]]

ITERASI 6

Q =
[[ 0.99999624 -0.00274346]
 [ 0.00274346  0.99999624]]

R =
[[2.9999

## menggunakan pecahan

In [9]:
import sympy as sp

def qr_decomposition(A):

    n = A.rows

    Q = sp.zeros(n, n)
    R = sp.zeros(n, n)

    for j in range(n):

        v = A[:, j]

        for i in range(j):

            R[i, j] = (Q[:, i].T * A[:, j])[0]

            v = v - R[i, j] * Q[:, i]

        R[j, j] = sp.sqrt((v.T * v)[0])

        Q[:, j] = v / R[j, j]

    return Q, R

def qr_iteration(A, jumlah_iterasi=10):

    Ak = A

    print("A0 =")
    sp.pprint(Ak)
    print()

    for k in range(jumlah_iterasi):

        print("=" * 40)
        print("ITERASI", k + 1)

        Q, R = qr_decomposition(Ak)

        print("\nQ =")
        sp.pprint(Q)

        print("\nR =")
        sp.pprint(R)

        # Ak+1 = RQ
        Ak = sp.simplify(R * Q)

        print("\nA{} =".format(k + 1))
        sp.pprint(Ak)
        print()

    return Ak



In [10]:
A = sp.Matrix([
    [2, 1],
    [1, 2]
])

hasil = qr_iteration(A, 10)

print("=" * 40)
print("MATRIKS AKHIR")
sp.pprint(hasil)

print("\nEIGENVALUE:")
sp.pprint(hasil.diagonal())

A0 =
⎡2  1⎤
⎢    ⎥
⎣1  2⎦

ITERASI 1

Q =
⎡2⋅√5  -√5 ⎤
⎢────  ────⎥
⎢ 5     5  ⎥
⎢          ⎥
⎢ √5   2⋅√5⎥
⎢ ──   ────⎥
⎣ 5     5  ⎦

R =
⎡    4⋅√5⎤
⎢√5  ────⎥
⎢     5  ⎥
⎢        ⎥
⎢    3⋅√5⎥
⎢0   ────⎥
⎣     5  ⎦

A1 =
⎡14/5  3/5⎤
⎢         ⎥
⎣3/5   6/5⎦

ITERASI 2

Q =
⎡14⋅√205  -3⋅√205 ⎤
⎢───────  ────────⎥
⎢  205      205   ⎥
⎢                 ⎥
⎢3⋅√205   14⋅√205 ⎥
⎢──────   ─────── ⎥
⎣ 205       205   ⎦

R =
⎡√205  12⋅√205⎤
⎢────  ───────⎥
⎢ 5      205  ⎥
⎢             ⎥
⎢      3⋅√205 ⎥
⎢ 0    ────── ⎥
⎣        41   ⎦

A2 =
⎡122       ⎤
⎢───   9/41⎥
⎢41        ⎥
⎢          ⎥
⎢       42 ⎥
⎢9/41   ── ⎥
⎣       41 ⎦

ITERASI 3

Q =
⎡122⋅√14965  -9⋅√14965 ⎤
⎢──────────  ──────────⎥
⎢  14965       14965   ⎥
⎢                      ⎥
⎢ 9⋅√14965   122⋅√14965⎥
⎢ ────────   ──────────⎥
⎣  14965       14965   ⎦

R =
⎡√14965  36⋅√14965⎤
⎢──────  ─────────⎥
⎢  41      14965  ⎥
⎢                 ⎥
⎢        3⋅√14965 ⎥
⎢  0     ──────── ⎥
⎣          365    ⎦

A3 =
⎡1094  27 ⎤
⎢────  ───⎥
⎢365   